version: "3"
services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "RZntaN.RZntaNdREJNdRE"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
  urlshortener-client:
    build: .
    ports:
      - "5137:80"